import React, { useState } from 'react';
import type { SonarDetection } from '../types/sonar';
import { Maximize2, X } from 'lucide-react';

interface SonarCanvasProps {
  imageUrl: string;
  annotatedImageUrl?: string;
  detections: SonarDetection[];
  onSelectDetection?: (detection: SonarDetection) => void;
  selectedDetectionId?: string;
}

export const SonarCanvas: React.FC<SonarCanvasProps> = ({
  imageUrl,
  annotatedImageUrl,
  detections,
  onSelectDetection,
  selectedDetectionId,
}) => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  // If the backend generated an annotated plot image directly with YOLO11n, display it directly
  const displayUrl = annotatedImageUrl || imageUrl;

  const refWidth = 600;
  const refHeight = 480;

  return (
    <>
      <div className="relative w-full h-[270px] bg-slate-950 rounded-xl overflow-hidden border border-slate-700/50 shadow-inner group flex items-center justify-center">
        <img
          src={displayUrl}
          alt="Side-Scan Sonar Acoustic Imagery"
          className="w-full h-full object-contain select-none"
        />

        {/* Client-side overlay if annotatedImageUrl was not generated by YOLO backend */}
        {!annotatedImageUrl &&
          detections.map((det) => {
            const [x1, y1, x2, y2] = det.bbox;
            const leftPct = (x1 / refWidth) * 100;
            const topPct = (y1 / refHeight) * 100;
            const widthPct = ((x2 - x1) / refWidth) * 100;
            const heightPct = ((y2 - y1) / refHeight) * 100;

            const isSelected = selectedDetectionId === det.id || detections.length === 1;

            return (
              <div
                key={det.id}
                onClick={() => onSelectDetection && onSelectDetection(det)}
                style={{
                  left: `${leftPct}%`,
                  top: `${topPct}%`,
                  width: `${widthPct}%`,
                  height: `${heightPct}%`,
                }}
                className={`absolute cursor-pointer transition-all duration-150 group/box ${
                  isSelected
                    ? 'border-2 border-amber-400 shadow-[0_0_12px_rgba(245,158,11,0.7)]'
                    : 'border border-amber-500/70 hover:border-amber-300'
                }`}
              >
                <div className="absolute -top-6 left-0 bg-amber-400 text-slate-950 text-[10px] font-bold px-1.5 py-0.5 rounded-t-sm whitespace-nowrap shadow-xs flex items-center gap-1">
                  <span>{det.className}</span>
                  <span className="opacity-90">{det.confidence.toFixed(2)}</span>
                </div>
              </div>
            );
          })}

        <button
          onClick={() => setIsModalOpen(true)}
          title="Fullscreen Sonar Inspection"
          className="absolute top-2.5 right-2.5 p-1.5 rounded-lg bg-slate-900/70 hover:bg-slate-900 text-white/80 hover:text-white backdrop-blur-xs transition-colors border border-white/10 shadow-sm cursor-pointer"
        >
          <Maximize2 className="w-4 h-4" />
        </button>
      </div>

      {/* Modal */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 bg-slate-950/85 backdrop-blur-md flex items-center justify-center p-4">
          <div className="relative max-w-4xl w-full bg-slate-900 border border-slate-700 rounded-2xl overflow-hidden shadow-2xl">
            <div className="flex items-center justify-between px-5 py-3 border-b border-slate-800 bg-slate-900/80">
              <div className="flex items-center gap-2">
                <span className="text-amber-400 font-mono text-sm font-semibold tracking-wider">
                  HIGH-RES ACOUSTIC INSPECTION
                </span>
                <span className="text-xs bg-slate-800 text-slate-400 px-2 py-0.5 rounded">
                  {detections.length} Target(s)
                </span>
              </div>
              <button
                onClick={() => setIsModalOpen(false)}
                className="p-1 rounded text-slate-400 hover:text-white hover:bg-slate-800 transition-colors cursor-pointer"
              >
                <X className="w-5 h-5" />
              </button>
            </div>

            <div className="relative p-4 flex items-center justify-center bg-black">
              <div className="relative max-w-full max-h-[70vh] overflow-hidden rounded-lg">
                <img
                  src={displayUrl}
                  alt="High resolution sonar"
                  className="max-h-[65vh] w-auto object-contain block"
                />
              </div>
            </div>

            <div className="px-5 py-3 border-t border-slate-800 bg-slate-900/90 text-xs text-slate-400 flex items-center justify-between">
              <div>
                Target:{' '}
                <span className="text-white font-medium">
                  {detections[0]?.className || 'None Detected'}
                </span>{' '}
                | Confidence:{' '}
                <span className="text-amber-400 font-medium">
                  {detections[0] ? `${Math.round(detections[0].confidence * 100)}%` : 'N/A'}
                </span>
              </div>
              <div className="font-mono text-slate-500">
                {detections[0]
                  ? `Footprint: ${detections[0].pixelDimensions.width} × ${detections[0].pixelDimensions.height} px`
                  : 'Clean Seabed'}
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
};
